version: '3'

services:
  dev_container:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./env/dev/Dockerfile
    ports:
      - 8000:8000
    environment:
      - SERVER_PORT=8000
    volumes:
      - ./:/home/dev/hygo-tryal
      - ~/.ssh:/home/dev/.ssh:ro
      - ~/.gitconfig:/home/dev/.gitconfig:ro
