name: hugo

on:
  push:
    branches:
      - master
      - int/**

jobs:
  build:
    name: build hugo
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Hugo build
      uses: klakegg/actions-hugo@1.0.0
      with:
        source: src/

